### ISSUE TITLE
support for user locking

### ISSUE THREAD

**Issue by jbe-dw** [Worteks/lsc-fusiondirectory-plugin#1]
Hi,

Thanks for your job. I suppose it's intended to work with 1.4 though. Do you think that you might support user locking in this plugin ?
As I see in the  [REST API documentation](https://rest-api.fusiondirectory.info/#operation/setLockState), it uses a different URI and looking at your code it's not supported. I may be wrong because I don't know about Java.

Regards
Jerome

**Comment by coudot** [comment]
Hello,

yes it uses FD 1.4 REST API : https://rest-api.fusiondirectory.info/

I don't know how we could handle locking, as we only map attributes from source to destination.

**Comment by jbe-dw** [comment]
Hello Clement,

Such a rapid answer ! I asked for help with account locking sync on the lsc-project irc and made it work. It doesn't fit well with fusion directory though (the locking toggle button is not in sync with the account status). The team pointed me to this new plugin page, and I wanted to give a try.

Looking at your answer the problem is on the lsc side I guess. 

An Idea could be to handle a special attribute which would trigger a special function to toggle something instead of copying a value. 

If it's too deep changes, we can close the issue then. I'll deal with it a different way then.

**Comment by jbe-dw** [comment]
I may just sync status to a csv file and make the api call with a script parsing it inside a cron job.
